/*
 * File:           PadraoScanner.java
 * Generated from: padrao.dtd
 * Date:           29 de Novembro de 2006  13:24
 *
 * @author  mjpereira
 * @version generated by NetBeans XML module
 */
package br.org.flem.fwe.menu;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NamedNodeMap;
import  org.w3c.dom.Attr;
import org.w3c.dom.NodeList;
import org.w3c.dom.Node;


/**
 *
 * This is a scanner of DOM tree.
 *
 * Example:
 * <pre>
 *     javax.xml.parsers.DocumentBuilderFactory builderFactory = javax.xml.parsers.DocumentBuilderFactory.newInstance();
 *     javax.xml.parsers.DocumentBuilder builder = builderFactory.newDocumentBuilder();
 *     org.w3c.dom.Document document = builder.parse (new org.xml.sax.InputSource (???));
 *     <font color="blue">PadraoScanner scanner = new PadraoScanner (document);</font>
 *     <font color="blue">scanner.visitDocument();</font>
 * </pre>
 *
 * @see org.w3c.dom.Document
 * @see org.w3c.dom.Element
 * @see org.w3c.dom.NamedNodeMap
 */
public class PadraoScanner {
    /**
     * org.w3c.dom.Document document
     */
    private Document document;
    
    /**
     * Create new PadraoScanner with org.w3c.dom.Document.
     */
    public PadraoScanner(Document document) {
        this.document = document;
    }
    
    /**
     * Scan through org.w3c.dom.Document document.
     */
    public Grupo visitDocument() {
        Element element = document.getDocumentElement();
        return visitElement_grupo(element);
    }
    
    /**
     * grupo.
     */
    Grupo visitElement_grupo(Element element) { // <grupo>
        Grupo grupo = new Grupo();
        NamedNodeMap attrs = element.getAttributes();
        for (int i = 0; i < attrs.getLength(); i++) {
            Attr attr = (Attr)attrs.item(i);
            if (attr.getName().equals("nome")) { // <grupo nome="???">
                grupo.setNome(attr.getValue());
            }
        }
        NodeList nodes = element.getChildNodes();
        for (int i = 0; i < nodes.getLength(); i++) {
            Node node = nodes.item(i);
            switch (node.getNodeType()) {
                case Node.ELEMENT_NODE:
                    Element nodeElement = (Element)node;
                    if (nodeElement.getTagName().equals("menu")) {
                        grupo.getMenus().add(visitElement_menu(nodeElement));
                    }
                    break;
            }
        }
        return grupo;
    }
    
    /**
     * Scan through org.w3c.dom.Element named menu.
     */
    Menu visitElement_menu(Element element) { // <menu>
        Menu menu = new Menu();
        NamedNodeMap attrs = element.getAttributes();
        for (int i = 0; i < attrs.getLength(); i++) {
            Attr attr = (Attr)attrs.item(i);
            if (attr.getName().equals("nome")) { // <menu nome="???">
                menu.setNome(attr.getValue());
            }
        }
        NodeList nodes = element.getChildNodes();
        for (int i = 0; i < nodes.getLength(); i++) {
            Node node = nodes.item(i);
            switch (node.getNodeType()) {
                case Node.ELEMENT_NODE:
                    Element nodeElement = (Element)node;
                    if (nodeElement.getTagName().equals("item")) {
                        menu.getItens().add(visitElement_item(nodeElement));
                    }
                    break;
            }
        }
        return menu;
    }
    
    /**
     * Scan through org.w3c.dom.Element named item.
     */
    Item visitElement_item(Element element) { // <item>
        Item item = new Item();
        NamedNodeMap attrs = element.getAttributes();
        for (int i = 0; i < attrs.getLength(); i++) {
            Attr attr = (Attr)attrs.item(i);
            if (attr.getName().equals("perfil")) { // <item perfil="???">
                item.setPerfil(attr.getValue());
            }
            if (attr.getName().equals("href")) { // <item href="???">
                item.setHref(attr.getValue());
            }
            if (attr.getName().equals("nome")) { // <item nome="???">
                item.setNome(attr.getValue());
            }
        }
        return item;
    }
    
    
}
